name: Glob Tests
on:
  push:
    paths:
      - "src/**"
      - "build.zig"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "build.zig"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2

      - name: Build and test Glob
        run: zig build test --summary all
