name: Glob Tests
on:
  push:
    paths:
      - "src/**"
      - "build.zig"
      - "build.zig.zon"
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
      - "build.zig"
      - "build.zig.zon"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2
        with:
          version: 0.17.0-dev.1893+78e3b1c73

      - name: Check formatting
        run: zig fmt --check .

      - name: Test
        run: zig build test --summary all
